name: RDP_PROJECT_SAMP

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update & Install XFCE + RDP
      run: |
        sudo apt update -y
        sudo apt install -y xfce4 xfce4-goodies xrdp
        sudo systemctl enable xrdp
        sudo adduser github
        echo "github:123456" | sudo chpasswd
        sudo usermod -aG sudo github
        echo xfce4-session > /home/github/.xsession
        sudo cp /home/github/.xsession /etc/skel
        sudo systemctl restart xrdp

    - name: Install Ngrok & Set Token
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok -y
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok Tunnel
      run: |
        ngrok tcp 3389 > ngrok.log &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels | grep -o "tcp://[0-9\.]*:[0-9]*"
