name: RDP_PROJECT_SAMP

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jalankan RDP
    steps:
    - name: Update & Install
      run: |
        sudo apt update
        sudo apt install -y qemu qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
        
    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok

    - name: Autentikasi Ngrok
      run: |
        ngrok config add-authtoken 2vsOCRL4zDkVRZoXkLvzhJbYt23_5VrY3CWKBsAwK4CM5ekM8

    - name: Jalankan RDP
      run: |
        sudo apt install xfce4 xfce4-goodies xrdp -y
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo ufw allow 3389
        ngrok tcp 3389
